version: "3"

services:
  web:
    build:
      context: .
      args:
        APP_DIR: /opt/espn-ffb
        CONFIG_DIR: /etc/opt/espn-ffb
        LOG_BASE_DIR: /var/log/espn-ffb
    volumes:
      # Store web logs in a local host directory
      - ./docker/data/logs/web:/var/log/espn-ffb
      # Store web logs in a named Docker volume
      # - espn_ffb_logs:${LOG_BASE_DIR}
    networks:
      - espn-ffb
    ports:
      - 5000:5000
    restart: on-failure
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    volumes:
      # Store db data in a local host directory
      - ./docker/data/db:/var/lib/postgresql/data
      # Store db data in a named Docker volume
      # - espn_ffb_db:/var/lib/postgresql/data
    networks:
      - espn-ffb
    restart: on-failure
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

networks:
  espn-ffb:
